project_id = "uslkpijmsudubulkuxve"

[functions.elevenlabs-tts]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false
